In [1]:
import numpy as np 


In [5]:
arr = np.array([10,20,30,40,50,60])
arr 

array([10, 20, 30, 40, 50, 60])

In [6]:
type(arr)

numpy.ndarray

In [9]:
## similar type data insert 
arr = np.array([10,20,30,40,50,60,100.25,'upflairs'])
arr 

array(['10', '20', '30', '40', '50', '60', '100.25', 'upflairs'],
      dtype='<U32')

In [10]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
### dimesion 
arr.ndim 

1

In [13]:
arr.shape 

(10,)

In [17]:
arr = [[1,2,3],[4,5,6]]
arr2 = np.array(arr)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape 

(2, 3)

In [ ]:
# 2d 
# [1d,1d,1d]

# 3d 
# [2d,2d,2d]



In [3]:
arr = np.array([10,20,30,40,50,60])
arr 

array([10, 20, 30, 40, 50, 60])

In [7]:
arr[-2] 

50

In [8]:
np.arange(21)  # single dimension 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.linspace(2,8,10)  # in between 2 to 8 , create array with 10 items

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [21]:
np.linspace(5,10)

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [32]:
import random

In [36]:
np.random.randint((5,2))

array([3, 0])

In [37]:
np.random.random(10)

array([0.40858092, 0.0246191 , 0.52670341, 0.65067157, 0.98827069,
       0.94153516, 0.72219973, 0.51200833, 0.37687931, 0.17759757])

In [42]:
np.arange(22).reshape(2,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [ ]:
11 * 2 

In [43]:
12*5

60

In [49]:
arr = np.arange(60).reshape(12,5)
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [54]:
b =  arr.ravel() 
b 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [56]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [60]:
arr.reshape(60,) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [63]:
arr = np.array([10,45,63,85,96,4,52,2,36,41])
arr 

array([10, 45, 63, 85, 96,  4, 52,  2, 36, 41])

In [66]:
arr[1::-1]

array([45, 10])

In [2]:
arr = np.arange(60).reshape(12,5)
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [5]:
arr[2]  # row 

array([10, 11, 12, 13, 14])

In [9]:
arr[0:3,3:5]    # [starting:stoping:step  point,starting:ending:step ]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [11]:
arr[4:6,0:2]   

array([[20, 21],
       [25, 26]])

In [13]:
arr[9:11,2:4]

array([[47, 48],
       [52, 53]])

In [31]:
arr[row,column]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
arr[-1][-1]


59

In [28]:
arr[-1,-1]

59

In [34]:
# arr[row,column] 

# 3d  = [2d,2d,2d,2d]

arr = np.random.randint(10,50,(5,3,3))
arr 

array([[[34, 34, 32],
        [23, 40, 36],
        [22, 21, 20]],

       [[39, 16, 16],
        [42, 36, 47],
        [11, 31, 23]],

       [[47, 33, 49],
        [30, 13, 16],
        [32, 23, 13]],

       [[30, 49, 43],
        [25, 17, 20],
        [37, 18, 46]],

       [[27, 37, 13],
        [35, 14, 25],
        [24, 33, 34]]])

In [38]:
arr.shape    # (5, 3, 3)   (5,3)
# (table , row , column )

(5, 3, 3)

In [44]:
arr[4][row,column]

array([[27, 37, 13],
       [35, 14, 25],
       [24, 33, 34]])

In [53]:
# arr[table,row,column]
arr[0]

array([[34, 34, 32],
       [23, 40, 36],
       [22, 21, 20]])

In [51]:
arr 

array([[[34, 34, 32],
        [23, 40, 36],
        [22, 21, 20]],

       [[39, 16, 16],
        [42, 36, 47],
        [11, 31, 23]],

       [[47, 33, 49],
        [30, 13, 16],
        [32, 23, 13]],

       [[30, 49, 43],
        [25, 17, 20],
        [37, 18, 46]],

       [[27, 37, 13],
        [35, 14, 25],
        [24, 33, 34]]])

In [56]:
arr[0,0,0] = 500

In [57]:
arr 

array([[[500,  34,  32],
        [ 23,  40,  36],
        [ 22,  21,  20]],

       [[ 39,  16,  16],
        [ 42,  36,  47],
        [ 11,  31,  23]],

       [[ 47,  33,  49],
        [ 30,  13,  16],
        [ 32,  23,  13]],

       [[ 30,  49,  43],
        [ 25,  17,  20],
        [ 37,  18,  46]],

       [[ 27,  37,  13],
        [ 35,  14,  25],
        [ 24,  33,  34]]])

In [73]:
# metrics operation  

ar1 = np.array([2,4,6])
ar2 = np.array([[2,5,3],[7,8,9]])
ar2  # [2,4,6]

array([[2, 5, 3],
       [7, 8, 9]])

In [74]:
ar2 + ar1 
        

array([[ 4,  9,  9],
       [ 9, 12, 15]])

In [66]:
ar1 + ar2   

array([4, 6, 8])

In [82]:
arr = np.random.randint(2,10,(7,3))
arr  

array([[2, 3, 3],
       [8, 7, 9],
       [4, 6, 2],
       [8, 9, 4],
       [4, 9, 5],
       [5, 7, 3],
       [6, 4, 3]])

In [81]:
arr.T 

array([[8, 9, 3, 9, 5, 2, 8],
       [5, 3, 5, 7, 4, 8, 9],
       [6, 6, 5, 6, 9, 8, 7]])

In [86]:
ar1 = np.array([2,4,6])
ar2 = np.array([7,8,9])
ar3 = np.array([[2,5,3],[7,8,9]])

In [92]:
ar2 

array([7, 8, 9])

In [93]:
ar3 

array([[2, 5, 3],
       [7, 8, 9]])

In [ ]:
# np.concatenate()  # axis = 1 horizontally , ver

In [103]:
np.vstack((ar2,ar3))  # np.hstack()

array([[7, 8, 9],
       [2, 5, 3],
       [7, 8, 9]])

In [104]:
arr1 = np.array([[2,5,6],[7,8,9]])
arr2  = np.array([[2,5,6],[7,8,9]])


In [105]:
arr1

array([[2, 5, 6],
       [7, 8, 9]])

In [106]:
arr2 

array([[2, 5, 6],
       [7, 8, 9]])

In [110]:
np.hstack((arr1.T,arr2.T))

# arr1.shape , arr2.shape 

array([[2, 7, 2, 7],
       [5, 8, 5, 8],
       [6, 9, 6, 9]])

In [112]:
arr = np.random.randint(1,200,500)
arr 

array([162, 157,  97,  31,  57,  46,  39,  58,  21, 197, 148,  41, 136,
        62, 183,  77,  74, 120,  83, 112, 100,  73, 133, 117, 154, 145,
       122, 111,  95,  78, 132, 124, 194, 127,  74, 151, 161, 181,  45,
       143,   9, 171, 121,  66, 182,  14, 161,   9, 146,  32, 131, 140,
        45,  26, 153, 174, 168, 128,  83,  83, 193,  19, 179,  27, 134,
       158, 163, 195,  83, 161,  41,  76,  63,  33, 143, 193, 147, 178,
        65,  34, 135, 181, 145, 187, 192, 158, 121,  33, 122, 107,  99,
        84, 171,  58, 158,  24,  29, 107, 184, 119, 199,  41,  71, 199,
       162, 133, 193, 175, 130,  74,   8, 123, 186,  44,  24,  82,  89,
       138, 156, 141,  98,  96, 114, 194, 107,  41, 157,  98,  76,  49,
       139, 152, 149, 177,  50,  96,  86, 137, 156,   4,   1, 135,  42,
        62, 145,  46,  95, 117,  67, 155,  58, 161, 118,  37, 158,  73,
        97,  56, 126,   6, 141,  87, 198, 124,  34, 189, 195,  99,  63,
       190,   4,  58,  28, 188,  22,  45, 126,  17,  85,  35, 14

In [116]:
arr.mean()  # min,max , sum , mean 

103.812

In [119]:
# arr   # filter all are item, that > 
for i in arr:
    if i>100:
        print(i)

162
157
197
148
136
183
120
112
133
117
154
145
122
111
132
124
194
127
151
161
181
143
171
121
182
161
146
131
140
153
174
168
128
193
179
134
158
163
195
161
143
193
147
178
135
181
145
187
192
158
121
122
107
171
158
107
184
119
199
199
162
133
193
175
130
123
186
138
156
141
114
194
107
157
139
152
149
177
137
156
135
145
117
155
161
118
158
126
141
198
124
189
195
190
188
126
146
101
199
137
142
138
125
103
197
179
151
144
197
198
132
181
184
126
143
102
183
147
126
193
111
194
155
123
193
155
158
160
124
189
101
165
163
138
178
138
164
136
135
166
181
136
123
117
141
159
181
105
147
172
103
180
153
115
172
176
196
164
135
162
137
187
136
163
173
129
173
143
138
140
136
126
176
103
151
169
158
160
156
176
159
149
161
179
155
169
176
105
153
122
190
143
136
155
143
175
180
127
106
189
124
196
147
132
152
173
125
188
101
113
158
186
186
140
113
141
153
186
166
117
109
124
125
190
141
153
112
163
121
141
125
183
123
158
188
166
172
194
133
103
190
155
112
111
129
159
102
182
160
155


In [131]:
arr[arr>100]

array([162, 157, 197, 148, 136, 183, 120, 112, 133, 117, 154, 145, 122,
       111, 132, 124, 194, 127, 151, 161, 181, 143, 171, 121, 182, 161,
       146, 131, 140, 153, 174, 168, 128, 193, 179, 134, 158, 163, 195,
       161, 143, 193, 147, 178, 135, 181, 145, 187, 192, 158, 121, 122,
       107, 171, 158, 107, 184, 119, 199, 199, 162, 133, 193, 175, 130,
       123, 186, 138, 156, 141, 114, 194, 107, 157, 139, 152, 149, 177,
       137, 156, 135, 145, 117, 155, 161, 118, 158, 126, 141, 198, 124,
       189, 195, 190, 188, 126, 146, 101, 199, 137, 142, 138, 125, 103,
       197, 179, 151, 144, 197, 198, 132, 181, 184, 126, 143, 102, 183,
       147, 126, 193, 111, 194, 155, 123, 193, 155, 158, 160, 124, 189,
       101, 165, 163, 138, 178, 138, 164, 136, 135, 166, 181, 136, 123,
       117, 141, 159, 181, 105, 147, 172, 103, 180, 153, 115, 172, 176,
       196, 164, 135, 162, 137, 187, 136, 163, 173, 129, 173, 143, 138,
       140, 136, 126, 176, 103, 151, 169, 158, 160, 156, 176, 15

In [137]:
arr.min()

1

In [139]:
np.unique(arr).shape  ### unique item fetch 

(186,)

In [142]:
len(set(np.unique(arr)))

186

In [144]:
arr.min()

1

In [145]:
np.argmin(arr)   # minimum item index 

140

In [146]:
arr[140]

1

In [147]:
np.argmax(arr)   # 

100

In [157]:
arr = np.array([4,7,1])
arr 

array([4, 7, 1])

In [149]:
arr.sort()

In [153]:
arr


array([1, 4, 7, 8])

In [158]:
arr 

array([4, 7, 1])

In [159]:
np.argsort(arr)

array([2, 0, 1], dtype=int64)

In [162]:
arr = np.array([1,2,3])
arr 

array([1, 2, 3])

In [163]:
np.argsort(arr)

array([0, 1, 2], dtype=int64)

In [170]:
np.random.randint(2,200,(10,5))

array([[180, 158,   9, 117,  90],
       [  3,  84,  59, 185,  28],
       [168, 176, 194, 113,  11],
       [154,  30, 185, 160, 181],
       [  9,  11,  43, 128, 142],
       [ 20,  21,  80, 120, 128],
       [133, 123,  48, 195, 123],
       [178,  78, 104,  48, 137],
       [154, 139,  77, 152,  80],
       [198, 148, 131,   9, 147]])

In [171]:
import random 

In [177]:
random.randint(5,10)

8

In [173]:
random.random()

0.42616078569295013

In [209]:
ls = [2,5,8,7,4,9,6,3,2,5,8,7,4]
random.choice(ls)

2

In [221]:
random.choices(ls,k=3)

[8, 3, 3]

In [222]:
# time , datetime 
import time 

In [223]:
time.localtime()

time.struct_time(tm_year=2024, tm_mon=5, tm_mday=25, tm_hour=18, tm_min=20, tm_sec=16, tm_wday=5, tm_yday=146, tm_isdst=0)

In [ ]:
def func1(): 
    pass 

def func2(): 
    pass 

def func3(): 
    pass 

def func4(): 
    pass 
func1()
func2()
func3()
func4()

##  top to down left to right  


In [ ]:
data science == > 

In [225]:
np.sqrt(9)  <== 

def squar_root():
    

3.0

In [ ]:
project , pandas ,  flask 